import type { Meta, StoryObj } from "@storybook/react";
import { TextArea } from "./index";

const meta: Meta<typeof TextArea> = {
  title: "TextArea/TextArea",
  component: TextArea,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;

type Story = StoryObj<typeof meta>;

export const Text_Area: Story = {};

export const Testing: Story = {
  args: {
    id: "responsive-textarea",
    placeholder: "Enter your message...",
    fontFamily: "Arial, sans-serif",
    fontSize: "16px",
    textAlign: "left",
    background: "white",
    border: "1px solid #ccc",
    padding: "10px",
    borderRadius: "5px",
    color: "black",
    focusBorder: "2px solid blue",
    placeholderColor: "grey",
    width: "100%",
    height: "100px",
    xxsWidth: "90%",
    xsWidth: "95%",
    smWidth: "100%",
    mdWidth: "80%",
    lgWidth: "70%",
    xlWidth: "60%",
    twoXlWidth: "50%",
    threeXlWidth: "45%",
    fourXlWidth: "40%",
    fiveXlWidth: "35%",
    sixXlWidth: "30%",
    xxsHeight: "80px",
    xsHeight: "85px",
    sHeight: "90px",
    mHeight: "95px",
    lgHeight: "110px",
    xlHeight: "120px",
    twoXlHeight: "130px",
    threeXlHeight: "140px",
    fourXlHeight: "150px",
    fiveXlHeight: "160px",
    sixXlHeight: "170px",
    xxsFontSize: "14px",
    xsFontSize: "15px",
    sFontSize: "16px",
    mFontSize: "17px",
    lgFontSize: "18px",
    xlFontSize: "19px",
    twoXlFontSize: "20px",
    threeXlFontSize: "21px",
    fourXlFontSize: "22px",
    fiveXlFontSize: "23px",
    sixXlFontSize: "24px",
    xxsMargin: "5px",
    xsMargin: "10px",
    sMargin: "15px",
    mMargin: "20px",
    lgMargin: "25px",
    xlMargin: "30px",
    twoXlMargin: "35px",
    threeXlMargin: "40px",
    fourXlMargin: "45px",
    fiveXlMargin: "50px",
    sixXlMargin: "55px",
    xxsPadding: "5px",
    xsPadding: "10px",
    sPadding: "15px",
    mPadding: "20px",
    lgPadding: "25px",
    xlPadding: "30px",
    twoXlPadding: "35px",
    threeXlPadding: "40px",
    fourXlPadding: "45px",
    fiveXlPadding: "50px",
    sixXlPadding: "55px",
    xxsBorderRadius: "2px",
    xsBorderRadius: "3px",
    sBorderRadius: "4px",
    mBorderRadius: "5px",
    lgBorderRadius: "6px",
    xlBorderRadius: "7px",
    twoXlBorderRadius: "8px",
    threeXlBorderRadius: "9px",
    fourXlBorderRadius: "10px",
    fiveXlBorderRadius: "11px",
    sixXlBorderRadius: "12px",
  },
};
