import type { Meta, StoryObj } from "@storybook/react";
import { PasswordInput } from "./index";

const meta: Meta<typeof PasswordInput> = {
  title: "Inputs/PasswordInput",
  component: PasswordInput,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;

type Story = StoryObj<typeof meta>;

const responsiveSettings = {
  xxs: {
    fontSize: "10px",
    margin: "2px",
    padding: "4px",
    width: "100px",
    height: "20px",
    borderRadius: "3px",
    iconFontSize: "12px",
  },
  xs: {
    fontSize: "12px",
    margin: "3px",
    padding: "6px",
    width: "120px",
    height: "22px",
    borderRadius: "4px",
    iconFontSize: "14px",
  },
  s: {
    fontSize: "14px",
    margin: "4px",
    padding: "8px",
    width: "140px",
    height: "24px",
    borderRadius: "5px",
    iconFontSize: "16px",
  },
  m: {
    fontSize: "16px",
    margin: "5px",
    padding: "10px",
    width: "160px",
    height: "26px",
    borderRadius: "6px",
    iconFontSize: "18px",
  },
  sm: {
    fontSize: "18px",
    margin: "6px",
    padding: "12px",
    width: "180px",
    height: "28px",
    borderRadius: "7px",
    iconFontSize: "20px",
  },
  l: {
    fontSize: "20px",
    margin: "7px",
    padding: "14px",
    width: "200px",
    height: "30px",
    borderRadius: "8px",
    iconFontSize: "22px",
  },
  md: {
    fontSize: "22px",
    margin: "8px",
    padding: "16px",
    width: "220px",
    height: "32px",
    borderRadius: "9px",
    iconFontSize: "24px",
  },
  tablet: {
    fontSize: "24px",
    margin: "9px",
    padding: "18px",
    width: "240px",
    height: "34px",
    borderRadius: "10px",
    iconFontSize: "26px",
  },
  tabletSm: {
    fontSize: "26px",
    margin: "10px",
    padding: "20px",
    width: "260px",
    height: "36px",
    borderRadius: "11px",
    iconFontSize: "28px",
  },
  lg: {
    fontSize: "28px",
    margin: "11px",
    padding: "22px",
    width: "280px",
    height: "38px",
    borderRadius: "12px",
    iconFontSize: "30px",
  },
  xl: {
    fontSize: "24px",
    margin: "12px",
    padding: "24px",
    width: "300px",
    height: "40px",
    borderRadius: "13px",
    iconFontSize: "32px",
  },
  twoXl: {
    fontSize: "32px",
    margin: "13px",
    padding: "26px",
    width: "320px",
    height: "42px",
    borderRadius: "14px",
    iconFontSize: "34px",
  },
  threeXl: {
    fontSize: "34px",
    margin: "14px",
    padding: "28px",
    width: "340px",
    height: "44px",
    borderRadius: "15px",
    iconFontSize: "36px",
  },
  fourXl: {
    fontSize: "36px",
    margin: "15px",
    padding: "30px",
    width: "360px",
    height: "46px",
    borderRadius: "16px",
    iconFontSize: "38px",
  },
  fiveXl: {
    fontSize: "38px",
    margin: "16px",
    padding: "32px",
    width: "380px",
    height: "48px",
    borderRadius: "17px",
    iconFontSize: "40px",
  },
  sixXl: {
    fontSize: "40px",
    margin: "17px",
    padding: "34px",
    width: "400px",
    height: "50px",
    borderRadius: "18px",
    iconFontSize: "42px",
  },
};
export const BorderTesting: Story = {
  args: {
    responsive: responsiveSettings,
    placeholder: "Enter your password",
    id: "passwordInput",
    backgroundColor: "#f0f0f0",
    fontWeight: "bold",
    width: "100%",
    height: "40px",
    focusBackgroundColor: "#ffffff",
    transition: "all 0.3s ease",
    iconColor: "#007bff",
    iconHoverColor: "#ff0000",
    color: "#333",
    placeholderColor: "#888888",
    focusPlaceholderColor: "#007bff",
    inputType: "borderBottom",
    borderBottomColor: "2px solid red",
    focusBorderBottomColor: "2px solid blue",
  },
};
