import type { Meta, StoryObj } from "@storybook/react";
import { Loader } from "./index";
import { Button } from "../Button_Components/Default";
import { Spinner } from "../Spinner";

const meta: Meta<typeof Loader> = {
  title: "Loaders/Loader",
  component: Loader,
  parameters: {
    layout: "centered",
  },
  tags: ["autodocs"],
};

export default meta;

type Story = StoryObj<typeof meta>;

const responsive = {
  xxs: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 390 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 390 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  xs: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 480 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 480 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  s: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 575 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 575 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  m: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 720 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 720 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  sm: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 860 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 860 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  l: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 992 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 992 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  md: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1100 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1100 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  tablet: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1024 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1024 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  tabletSm: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1200 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1200 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  lg: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1360 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1360 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  xl: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1520 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1520 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  twoXl: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1680 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1680 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  threeXl: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 1920 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 1920 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  fourXl: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 2560 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 2560 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  fiveXl: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 3840 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 3840 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
  sixXl: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    gap: "clamp(24px, 48 / 5120 * 100vw, 96px)",
    alignItems: "center",
    justifyContent: "center",
    fontSize: "clamp(16px, 32 / 5120 * 100vw, 64px)",
    borderRadius: "0px",
    position: "fixed",
    top: "0",
    left: "0",
    zIndex: "10",
  },
};

export const DefaultLoader: Story = {
  args: {
    text: "Default Loader",
    responsive: responsive,
    display: "flex",
    flexDirection: "column" as "column",
    backgroundColor: "#845EC2",
    spinner: <Spinner color="#22a6b3" size="128px" />,
    transition: "0.3s ease-in-out",
  },
};
