export const defaultFooterStyles = {
  backgroundColor: "transparent",
  linkColor: "#845EC2",
  linkHoverColor: "#4B4453",
  linkTextDecoration: "none",
  linkTransition: "0.3s ease-in-out",
  logoHref: "/",
  fontWeight: "700",
  fontFamily: "Helvetica",
  buttonText: "Authorithation",
  buttonBackgroundColor: "#845EC2",
  buttonColor: "white",
  buttonHoverColor: "none",
  hoverButtonBackgroundColor: "#4B4453",
  separatorBackgroundColor: "#845EC2",
};
