import { Meta, StoryObj } from "@storybook/react";
import logo from "../../Logo/logo-402d9f18.svg";
import {
  faInstagram,
  faFacebookF,
  faTwitter,
} from "@fortawesome/free-brands-svg-icons";
import { FooterSocial } from "./index";

const meta: Meta<typeof FooterSocial> = {
  title: "Footer_Components/FooterSocial",
  component: FooterSocial,
  parameters: {
    layout: "fullscreen",
  },
};

export default meta;

type Story = StoryObj<typeof FooterSocial>;

const responsive = {
  l: {
    // laptops and small desktops
    footerWidth: "100%",
    footerMargin: "0",
    containerWidth: "80%",
    containerMargin: "0 auto",
    logoWidth: "40px",
    logoHeight: "40px",
    gapNavigation: "15px",
    linkWidth: "120px",
    linkHeight: "30px",
    linkFontSize: "14px",
    linkMargin: "8px",
    linkBorderRadius: "8px",
    linkPadding: "8px 16px",
    buttonWidth: "140px",
    buttonHeight: "35px",
    buttonFontSize: "14px",
    buttonMargin: "8px",
    buttonBorderRadius: "8px",
    buttonPadding: "8px 16px",
    iconWidth: "24px",
    iconHeight: "24px",
    iconsContainerWidth: "350px",
    iconsContainerMargin: "10px auto",
    iconsContainerGap: "10px",
  },
  xl: {
    // large desktops
    footerWidth: "100%",
    footerMargin: "0",
    containerWidth: "75%",
    containerMargin: "0 auto",
    logoWidth: "60px",
    logoHeight: "60px",
    gapNavigation: "20px",
    linkWidth: "160px",
    linkHeight: "40px",
    linkFontSize: "16px",
    linkMargin: "10px",
    linkBorderRadius: "10px",
    linkPadding: "10px 20px",
    buttonWidth: "180px",
    buttonHeight: "45px",
    buttonFontSize: "16px",
    buttonMargin: "10px",
    buttonBorderRadius: "10px",
    buttonPadding: "10px 20px",
    iconWidth: "28px",
    iconHeight: "28px",
    iconsContainerWidth: "400px",
    iconsContainerMargin: "15px auto",
    iconsContainerGap: "15px",
  },
  twoXl: {
    // very large desktops
    footerWidth: "100%",
    footerMargin: "0",
    containerWidth: "70%",
    containerMargin: "0 auto",
    logoWidth: "80px",
    logoHeight: "80px",
    gapNavigation: "25px",
    linkWidth: "180px",
    linkHeight: "50px",
    linkFontSize: "18px",
    linkMargin: "12px",
    linkBorderRadius: "12px",
    linkPadding: "12px 24px",
    buttonWidth: "200px",
    buttonHeight: "55px",
    buttonFontSize: "18px",
    buttonMargin: "12px",
    buttonBorderRadius: "12px",
    buttonPadding: "12px 24px",
    iconWidth: "32px",
    iconHeight: "32px",
    iconsContainerWidth: "450px",
    iconsContainerMargin: "20px auto",
    iconsContainerGap: "20px",
  },
  threeXl: {
    footerWidth: "100%",
    footerMargin: "0",
    containerWidth: "100%",
    containerMargin: "0 auto",
    logoWidth: "100px",
    logoHeight: "100px",
    gapNavigation: "30px",
    linkWidth: "200px",
    linkHeight: "60px",
    linkFontSize: "20px",
    linkMargin: "15px",
    linkBorderRadius: "15px",
    linkPadding: "15px 30px",
    buttonWidth: "220px",
    buttonHeight: "60px",
    buttonFontSize: "20px",
    buttonMargin: "15px",
    buttonBorderRadius: "15px",
    buttonPadding: "15px 30px",
    iconWidth: "36px",
    iconHeight: "36px",
    iconsContainerWidth: "500px",
    iconsContainerMargin: "25px auto",
    iconsContainerGap: "25px",
  },
};

export const Default: Story = {
  args: {
    backgroundColorFooter: "#f8f9fa",
    transitionNavigation: "0.3s ease",
    logoHref: "#",
    logo: logo,
    links: [
      { text: "Home", href: "#" },
      { text: "About", href: "#" },
      { text: "Services", href: "#" },
      { text: "Contact", href: "#" },
    ],
    icons: [
      { iconHref: "https://instagram.com", icon: faInstagram },
      { iconHref: "https://facebook.com", icon: faFacebookF },
      { iconHref: "https://twitter.com", icon: faTwitter },
    ],
    buttonBackgroundColor: "#007bff",
    buttonFontWeight: "bold",
    buttonFontFamily: "Arial, sans-serif",
    buttonTextDecoration: "none",
    buttonText: "Subscribe",
    buttonHref: "#subscribe",
    buttonHoverBorder: "1px solid #0056b3",
    buttonBorder: "1px solid #007bff",
    buttonHoverColor: "#ffffff",
    buttonColor: "#ffffff",
    buttonTransition: "color 0.3s ease",
    hoverButtonBackgroundColor: "#0056b3",
    iconColor: "#333333",
    iconHoverColor: "red",
    logoStudioHref: "#studio",
    linkColor: "#555555",
    linkBackgroundColor: "#ffffff",
    linkFontWeight: "normal",
    linkFontFamily: "Arial, sans-serif",
    linkTextDecoration: "none",
    linkTransition: "background-color 0.3s ease",
    linkHoverBackgroundColor: "#eeeeee",
    linkHoverColor: "#333333",
    linkHoverBorder: "1px solid #cccccc",
    responsive: responsive,
  },
};
